version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_packageRead.zip .
      - zip -r9 ../deployment_packageEnrich.zip .
      - cd ..
      - zip -g deployment_package.zip lambdaFcnReadMovies.py
      - zip -g deployment_package.zip lambdaFcnEnrich.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name movies --zip-file fileb://deployment_packageRead.zip
      - aws lambda update-function-code --function-name enrichstore --zip-file fileb://deployment_packageEnrich.zip
      - echo "DONE!!"